### PR TITLE
travis: switch to roblabla/cargo-travis

### PR DESCRIPTION
**Pull request by hdhoang**
I have attempted a simple translation from travis-cargo to cargo-travis. Please verify that coveralls and doc are updated correctly.

### CODE REVIEW

**Comment by oschwald** [comment]
:+1:

**Comment by oschwald** [comment]
I'll merge to see if Travis builds it.

**Comment by oschwald** [comment]
Doh, Travis didn't seem to build after this.

**Comment by oschwald** [comment]
The YAML wasn't valid. I fixed that. It worked although the build time was pretty long.

**Comment by hdhoang** [comment]
*slap forehead*, thanks

**Comment by hdhoang** [comment]
hopefully the cache will shave off cargo-update and cargo-travis build time later on.

however it looks like coveralls fails after building kcov. I'll look at that later

**Pull request merged**
