### PR TITLE
Add `lookup_prefix` that also returns the prefix length for the node

### PR DESCRIPTION
**Pull request by vavrusa**
This is useful to discover the prefix length for given address for caching purposes.

### CODE REVIEW

**Comment by Mr-Click** [comment]
This is a very useful patch! I was just looking on how to extract network information and I found that someone already proposed it.
I hope it gets merged soon.

**Comment by oschwald** [comment]
This needs tests and to be rebased before it could be merged.

**Comment by oschwald** [comment]
This needs a rebase now. I am still happy to merge this if tests are added.

**Comment by vavrusa** [comment]
Hi! Thanks for being patient, it took me forever to get back to this. There's a test in the docstring, but I also added a separate unit test and rebased.

**Review by oschwald — APPROVED** [review]

**Comment by oschwald** [comment]
Thanks! I release 0.23.0 with this change.

**Pull request merged**
