### PR TITLE
Replace rustc_serialize with Serde

### PR DESCRIPTION
**Pull request by wezm**
I implemented Serde support. All the tests are passing for me (and CI)

### CODE REVIEW

**Comment by oschwald** [comment]
Wow, this looks great! Given its size, it might take me a couple of days to review. Thanks!

**Comment by oschwald** [comment]
When I run `example/lookup.rs` (after removing the unused crate), I get `thread 'main' panicked at 'not yet implemented', src/maxminddb/decoder.rs:70`

**Comment by wezm** [comment]
I just pushed some changes that get the example working. I added a test to cover this case but it didn't fail despite using the same code as the lookup example... There are two arms of `deserialize_any` that are still marked `unimplemented` I'll look into implementing these tonight.

**Comment by wezm** [comment]
Righto, improved and filled out the remaining arms of `deserialize_any`. Example and tests are running/passing.

Note: I moved the example to `examples` so that you can run it with `cargo run --example lookup`

**Comment by oschwald** [comment]
Thanks so much for the PR! It looked great. I merged it and did a release.

**Comment by wezm** [comment]
Excellent. Thanks for reviewing so quickly. :)

**Pull request merged**
